WebAppEs/Controllers/QCCheckController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using WebAppEs.Models;
using WebAppEs.Services;
using WebAppEs.ViewModel.QCCheck;

namespace WebAppEs.Controllers
{
    public class QCCheckController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IDataAccessService _dataAccessService;
        private readonly ILogger<AdminController> _logger;
        private IWebHostEnvironment Environment;
        private IConfiguration Configuration;

        public QCCheckController(UserManager<ApplicationUser> userManager,
                RoleManager<IdentityRole> roleManager,
                IDataAccessService dataAccessService, IWebHostEnvironment _environment, IConfiguration _configuration)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _dataAccessService = dataAccessService;
            Environment = _environment;
            Configuration = _configuration;
        }

        public IActionResult Index()
        {
            var employeeID = HttpContext.Session.GetString("EmployeeID");

            if (employeeID == null)
            {
                return RedirectToAction("Logout", "Account");
            }

            MobileRND_QcTaskHead_VM TaskHead = new MobileRND_QcTaskHead_VM();
            TaskHead.MobileRND_QcTaskHead_List = _dataAccessService.TaskHeadList(null, "");
            TaskHead.PartsModelViewModel = _dataAccessService.GetAllPartsModelList();
            return View(TaskHead);
        }

        public IActionResult CreateTask(Guid? Id)
        {
            var employeeID = HttpContext.Session.GetString("EmployeeID");

            if (employeeID == null)
            {
                return RedirectToAction("Logout", "Account");
            }

            List<MobileRND_QcTaskHeadDetails_VM> empty = new List<MobileRND_QcTaskHeadDetails_VM>();
            if (Id == null || Id == Guid.Empty)
            {
                MobileRND_QcTaskHead_VM TaskHead = new MobileRND_QcTaskHead_VM();
                TaskHead.PartsModelViewModel = _dataAccessService.GetAllPartsModelList();
                TaskHead.MobileRND_QcTaskHeadDetails_VM = empty;
                TaskHead.GetTopOrderValue = new MobileRND_QcTaskHeadDetails_VM();
                return View(TaskHead);
            }
            else
            {
                MobileRND_QcTaskHead_VM TaskHead = new MobileRND_QcTaskHead_VM();
                TaskHead = _dataAccessService.HeadWithDetails(Id);
                var topOrderValue = _dataAccessService.GetTopOrderValueForFalse(Id);
                if(topOrderValue!= null)
                {
                    TaskHead.GetTopOrderValue = topOrderValue;
                }
                else
                {
                    TaskHead.GetTopOrderValue = new MobileRND_QcTaskHeadDetails_VM();
                }
                
                TaskHead.PartsModelViewModel = _dataAccessService.GetAllPartsModelList();
                return View(TaskHead);
            }
        }

        [HttpPost]
        public IActionResult CreateTask(MobileRND_QcTaskHead_VM vm)
        {
            var employeeID = HttpContext.Session.GetString("EmployeeID");

            if (employeeID == null)
            {
                return RedirectToAction("Logout", "Account");
            }

            MobileRND_QcTaskHead_VM newhead = new MobileRND_QcTaskHead_VM();
               ClaimsPrincipal currentUser = this.User;
            var ID = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            Guid newGuid = Guid.Parse(ID);
            bool isSuperAdmin = currentUser.IsInRole("SuperAdmin");
            bool isAdmin = currentUser.IsInRole("Admin");

            var HedSubmit = false;
            var DetailsSubmit = false;
            //bool status = false;
            StatusModel status = new StatusModel();
            status.success = false;
            var LuserID = HttpContext.Session.GetString("Id");
            Guid newGuid2 = Guid.Parse(LuserID);
            
            var StoreHead = _dataAccessService.GetStoreHead(null, vm.ModelID, vm.LotNo);
            if(StoreHead == null)
            {
                ModelState.AddModelError("Error", "This model and lot wise record not found from store. Please add data from store then try again...");
                newhead = vm;
                newhead.MobileRND_QcTaskHeadDetails_VM = new List<MobileRND_QcTaskHeadDetails_VM>();
                newhead.GetTopOrderValue = new MobileRND_QcTaskHeadDetails_VM();
                newhead.PartsModelViewModel = _dataAccessService.GetAllPartsModelList();
                return View(newhead);
            }
            var StoreDetails = _dataAccessService.StoreHeadDetailsList(StoreHead.Id);

            MobileRND_QcTaskHead_VM head = new MobileRND_QcTaskHead_VM();
            

            head.ModelID = (Guid)vm.ModelID;
            head.LotNo = vm.LotNo;
            head.EmployeeID = employeeID;
            head.TaskType = vm.TaskType;
            head.LUser = newGuid2;
            head.LineNo = vm.LineNo;
            var taskHead = _dataAccessService.AddTaskHead(head);

            if(vm.TaskType != "random")
            {
                foreach (var item in StoreDetails)
                {
                    MobileRND_QcTaskHeadDetails_VM headdetails = new MobileRND_QcTaskHeadDetails_VM();
                    headdetails.EmployeeID = employeeID;
                    headdetails.TaskHeadID = taskHead.Id;
                    headdetails.StoreDetailsID = (Guid)item.Id;
                    head.LUser = newGuid2;
                    _dataAccessService.AddTaskHeadDetails(headdetails);
                }
            }
           
            newhead = _dataAccessService.HeadWithDetails(taskHead.Id);
            var tt = _dataAccessService.GetTopOrderValueForFalse(taskHead.Id);
            if(tt != null)
            {
                newhead.GetTopOrderValue = tt;
            }
            else
            {
                newhead.GetTopOrderValue = new MobileRND_QcTaskHeadDetails_VM();
            }
            newhead.PartsModelViewModel = _dataAccessService.GetAllPartsModelList();
           
            return View(newhead);
        }

        public JsonResult GetCurrentLocationForRandom(Guid TaskHeadID,  Guid ModelID, string lot, string Moduler, string feeder)
        {
            var item = _dataAccessService.GetTopOrderValueForRandom(TaskHeadID, ModelID, lot, Moduler, feeder);
            return Json(item);
        }

        public JsonResult GetCurrentLocation(Guid HeadID)
        {
            var item = _dataAccessService.GetTopOrderValueForFalse(HeadID);
            return Json(item);
        }

        public JsonResult UpdateQCScanData(Guid? Id, bool status)
        {
            var result = false;
            if (Id != Guid.Empty)
            {
                var r = _dataAccessService.UpdateSingelStatusFromQC((Guid)Id, status);
                result = r;
            }

            return Json(new { isSuccess = result });
        }

        public IActionResult AddQCRandomScanData(Guid? StoreDetailsId, Guid? TaskHeadID, bool status)
        {
            var employeeID = HttpContext.Session.GetString("EmployeeID");

            if (employeeID == null)
            {
                return RedirectToAction("Logout", "Account");
            }
            var LuserID = HttpContext.Session.GetString("Id");
            Guid newGuid2 = Guid.Parse(LuserID);
            
            var response = _dataAccessService.AddRandomDataStatusFromQC(StoreDetailsId, TaskHeadID, status, employeeID, newGuid2);

            var fullDetails = _dataAccessService.HeadWithDetails(response.TaskHeadID);
            var singeldata = fullDetails.MobileRND_QcTaskHeadDetails_VM.Where(x => x.Id == response.Id);
            fullDetails.MobileRND_QcTaskHeadDetails_VM = singeldata;
            return Json(fullDetails);
        }

    }
}

WebAppEs/Views/QCCheck/Index.cshtml
@model WebAppEs.ViewModel.QCCheck.MobileRND_QcTaskHead_VM
@{
    ViewData["Title"] = "QC Check";
}
<style>
    .bootstrap-select > .dropdown-toggle.bs-placeholder, .bootstrap-select > .dropdown-toggle.bs-placeholder:hover, .bootstrap-select > .dropdown-toggle.bs-placeholder:focus, .bootstrap-select > .dropdown-toggle.bs-placeholder:active {
        color: #000;
    }

    .bootstrap-select .dropdown-toggle:focus {
        outline: none !important;
        outline: none !important;
        outline-offset: -2px;
    }

    .bootstrap-select:not([class*="col-"]):not([class*="form-control"]):not(.input-group-btn) {
        width: 100%;
    }

    .badge-successs {
        display: inline-block;
        min-width: 10px;
        padding: 3px 7px;
        font-size: 12px;
        font-weight: 700;
        line-height: 1;
        color: #fff;
        text-align: center;
        white-space: nowrap;
        vertical-align: middle;
        background-color: #19a735;
        border-radius: 10px;
    }

    .badge-info {
        display: inline-block;
        min-width: 10px;
        padding: 3px 7px;
        font-size: 12px;
        font-weight: 700;
        line-height: 1;
        color: #fff;
        text-align: center;
        white-space: nowrap;
        vertical-align: middle;
        background-color: #19a735;
        border-radius: 10px;
    }

    .badge-Dangerr {
        display: inline-block;
        min-width: 10px;
        padding: 3px 7px;
        font-size: 12px;
        font-weight: 700;
        line-height: 1;
        color: #000;
        text-align: center;
        white-space: nowrap;
        vertical-align: middle;
        background-color: #ffca5e;
        border-radius: 10px;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="breadcomb-list">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                        <div class="breadcomb-wp">
                            <div class="breadcomb-icon">
                                <i class="notika-icon notika-form"></i>
                            </div>
                            <div class="breadcomb-ctn">
                                <h2 style="margin:13px;">QC Check</h2>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-3">
                        <div class="breadcomb-report">
                            <a data-toggle="tooltip" data-placement="left" asp-action="CreateTask" title="Add Task" class="btn"><i class="notika-icon notika-plus-symbol"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="form-example-wrap mg-t-30">
                <div class="cmp-tb-hd cmp-int-hd">
                    <h2>Check List</h2>
                </div>
                <div class="data-table-list">
                    <div class="table-responsive">
                        <table id="data-table-basicindex" class="table table-striped">
                            <thead style="background-color: #d7e3ef;">
                                <tr>
                                    <th>Date</th>
                                    <th>Line</th>
                                    <th>Model</th>
                                    <th>Lot</th>
                                    <th>C. Type</th>
                                    <th>Status</th>
                                    <th>Duration</th>
                                    <th>Employe ID</th>
                                    <th style="text-align:center">Action's</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.MobileRND_QcTaskHead_List)
                                {
                                    @if (item.StatusIsToday == false)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.DateString)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.LineNo)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.ModelName)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.LotNo)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.TaskType)
                                            </td>
                                            <td>
                                                @if (item.IsComplete == "Complete")
                                                {
                                                    <p class="badge-successs">
                                                        @Html.DisplayFor(modelItem => item.IsComplete)
                                                    </p>
                                                }
                                                else
                                                {
                                                    <span class="badge-Dangerr">
                                                        @Html.DisplayFor(modelItem => item.IsComplete)
                                                    </span>
                                                }
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Duration)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.EmployeeID)
                                            </td>
                                            <td style="text-align:center">
                                                <a style=" font-size: large; color: blue;" asp-action="CreateTask" asp-controller="QCCheck" asp-route-id="@item.Id"><i class="fa fa-edit"></i></a>
                                            </td>
                                    </tr>
                                    }
                                    else
                                    {
                                        <tr>
                                            <td style="color: #11009d; font-weight: bold;">
                                                @Html.DisplayFor(modelItem => item.DateString)
                                            </td>
                                            <td style="color: #11009d; font-weight: bold;">
                                                @Html.DisplayFor(modelItem => item.LineNo)
                                            </td>
                                            <td style="color: #11009d; font-weight: bold;">
                                                @Html.DisplayFor(modelItem => item.ModelName)
                                            </td>
                                            <td style="color: #11009d; font-weight: bold;">
                                                @Html.DisplayFor(modelItem => item.LotNo)
                                            </td>
                                            <td> 
                                                @Html.DisplayFor(modelItem => item.TaskType)
                                            </td>
                                            <td>
                                                @if (item.IsComplete == "Complete")
                                                {
                                                    <span class="badge-successs">
                                                        @Html.DisplayFor(modelItem => item.IsComplete)
                                                    </span>
                                                }
                                                else
                                                {
                                                    <span class="badge-Dangerr">
                                                        @Html.DisplayFor(modelItem => item.IsComplete)
                                                    </span>
                                                }
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Duration)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.EmployeeID)
                                            </td>
                                            <td style="text-align:center">
                                                <a style=" font-size: large; color: blue;" asp-action="CreateTask" asp-controller="QCCheck" asp-route-id="@item.Id"><i class="fa fa-edit"></i></a>
                                            </td>
                                    </tr>
                                    }
                                    
                                }
                                </tbody>
                            </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{
<script>
    $(document).ready(function () {
        $('#data-table-basicindex').dataTable({
            "order": [[0, "desc"]]
        });

    });
</script>
}
    